### ISSUE TITLE
Issue request: import of csv with paired keyword and expansion

### ISSUE THREAD

**Issue by low-decarie** [xmichelo/Beeftext#104]
Thanks for such a great tool!
It would be amazing to be able to bulk import/export a table containing keyword and expansion pairs.

**Comment by xmichelo** [comment]
Hi @low-decarie 

That's something I had in mind a long time ago and forgot to add it as a feature request. Thanks a lot.

In you case, what would be the source of your CSV file? Another text expanding software, I guess.

**Comment by low-decarie** [comment]
There are a few sources in mind.  Among other things, we have a document that has hundreds of commonly used acronyms and their explanation.  I would add an underscore to each acronym to create a keyword that would lead to the expansion of the acronym. I would also like to share Beeftext groups with colleagues.  Thanks again for such a great tool!

**Comment by xmichelo** [comment]
OK Thanks. 
I thinks I will implement CSV file support as a first step.

**Comment by rikblok** [comment]
This could also be great for sharing combo groups!  For example, I put some work into creating a list of LaTeX macros that map onto Unicode characters (eg. \alpha → α) and another for emojis (eg. :D → 😄).  Having a way to share these would bring the power of collaborative development to Beeftext.

**Comment by DustinWehr** [comment]
@rikblok you can use the script I wrote for TextExpander. You just need to replace the line
just need to replace line 
`SEPARATOR_STRING = "|"` 
with 
`SEPARATOR_STRING = ","`
and skip the first paragraph of instruction (which is how to export a "|"-separated values file from TextExpander).
Here's the script: https://repl.it/@DustinWehr/textExpanderToBeeftextpy 
The related issue: https://github.com/xmichelo/Beeftext/issues/116#issuecomment-457644503

**Comment by xmichelo** [comment]
I finally implemented CSV import and export. It will be included in Beeftext 5.0.

More info in the [dedicated wiki page](https://github.com/xmichelo/Beeftext/wiki/Import-and-export).

You can grab test builds if you are willing to test:
- [Installer](https://1drv.ms/u/s!AjydspuvJDSngZVirXfjTJ4kerwHpQ?e=bSgdCz).
- [Portable Edition](https://1drv.ms/u/s!AjydspuvJDSngZVj2IIWbLJNBpLu_Q?e=5RNrEc).

**Note**: the file format for combo lists has changed since the official 4.0 release, so if you rollback to the official release, you will get an error message on startup stating that the combo list file was created by a newer version of the application.  To fix that:
- Close Beeftext. 
- Open your combo list file (located by default at `%LOCALAPPDATA%\beeftext.org\Beeftext\comboList.json`). 
- Locate the key `fileFormatVersion` and change its value from 6 to 5.
- Save the file and relaunch Beeftext.
