### ISSUE TITLE
Blanks at the end of a snippet are not inserted in Outlook

### ISSUE THREAD

**Issue by MO92119** [xmichelo/Beeftext#115]
### Expected behavior
With keyword "HM" I want to insert the snippet "Hello Mr. " (including the blank at the end).

### Actual behavior
This does not work in Microsoft Outlook 365. Just "Hello Mr." (without the blank at the end) is inserted.
It works e.g. in Notepad, but as I use Outlook for emails, this would be very helpful.

### Operating system
Windows 10

**Comment by xmichelo** [comment]
Hi @MO92119. Thanks for the report. I will test that and will let you know if I can reproduce the issue.

**Comment by TerDale** [comment]
Hi all,
I confirm the issue, while using other apps than OL.  Looks like the snippet is trimmed before insertion.
Thanks in advance for the fix Xavier.

**Comment by xmichelo** [comment]
Hi @TerDale and @MO92119 

Do you have the **Use clipboard for combo substitution** option enabled?

I have a potential workaround in a related bug. Please have a look at issue #131. I have some test build that you might want to try.

**Comment by TerDale** [comment]
Hi @xmichelo,

Yes, I do.  I'll check your build, and will let you know.
Thanks in any case for your attempts to fix this issue.

**Comment by TerDale** [comment]
well... trying to reproduce the issue before testing your build, I just figured out that it appears fixed, likely by the 1.8 I installed recently!
My issue was a snippet with keyword "eg." and text replacement "e.g. ". At the time of my above comment, typing "eg." was replaced by "e.g.", while now it is properly replaced by "e.g. ". Dunno if it the same for OP, as my issue was not related to Outlook.

**Comment by xmichelo** [comment]
I replied in the wrong thread. So here is  the same text I posted on issue #131:

I could actually reproduce the issue when Beeftext uses the clipboard for combo substitution. The problem is a feature of Outlook (and other office apps) called Smart cut and paste. If you manually copy your snippet (with the space at then end) in the clipboard, and paste manually in Outlook, you will see that the space also disappear.
 
It is actually Outlook that is removing the space. To disable this, in the latest version, go to File ➜ Options ➜ Mail ➜ Editor Options ➜ Advanced and uncheck Use smart cut and paste.

The option also exists in Word.

Could you please confirm it solves the issue?

**Comment by MO92119** [comment]
> I replied in the wrong thread. So here is the same text I posted on issue #131:
> 
> > I could actually reproduce the issue when Beeftext uses the clipboard for combo substitution. The problem is a feature of Outlook (and other office apps) called _Smart cut and paste_. If you manually copy your snippet (with the space at then end) in the clipboard, and paste manually in Outlook, you will see that the space also disappear.
> > It is actually Outlook that is removing the space. To disable this, in the latest version, go to `File ➜ Options ➜ Mail ➜ Editor Options ➜ Advanced` and uncheck _Use smart cut and paste_.
> > The option also exists in Word.
> > Could you please confirm it solves the issue?

That solves the issue for me. Thank you very much!
