### ISSUE TITLE
cursor variable not work properly?

### ISSUE THREAD

**Issue by budaig** [xmichelo/Beeftext#123]
hi, nice work. thanks!

I setup like this, expecting the cursor to be at the front of the clipboard content,
![beef](https://user-images.githubusercontent.com/18586226/52516482-00e87a00-2c67-11e9-8730-f9990b9770f2.jpg)
but after triggering it, the cursor is still at the end.
Is there something wrong with my setups?
Thanks.

**Comment by xmichelo** [comment]
Hi @budaig.

No, your setup is correct, it's a bug in the application. Thank your for reporting.

**Comment by budaig** [comment]
@xmichelo thanks.
looking forward to the new version.

**Comment by xmichelo** [comment]
I was pretty sure it was linked to mixing #{cursor} and #{clipboard} but the problem was actually that #{cursor} didn't work when placed at the very beginning of a snippet.

@budaig I'm not planning a release soon, so if you want to test the fix, grab one of the following builds:

- [Installer](https://1drv.ms/u/s!AjydspuvJDSnu2yPu3RpQrbIi3ek).
- [Portable](https://1drv.ms/u/s!AjydspuvJDSnu2v0XR45OiRBZ_3g).

**Comment by budaig** [comment]
@xmichelo thanks very much.
this version fixed the cursor positioning.
