### ISSUE TITLE
Combo Picker Dialog doesn't work properly

### ISSUE THREAD

**Issue by lucius346346** [xmichelo/Beeftext#175]
**Expected behavior**
Win + Shift + Enter should show Combo Picker Dialog

**Actual behavior**
Dialog shows for fraction of second and disappears. It also paste some random combo.

Windows 7

**Comment by xmichelo** [comment]
Hi @lucius346346 

I'm off for the day, but I will test Beeftext on a Windows 7 virtual machine.

Thinking about it, it could be a problem with the Win+Shift combination. If I remember correctly, in Windows 7, this shortcut was reserved by the system to switch language and/or keyboard layout.

Have you tried changing the shortcut in the Preferences?

**Comment by xmichelo** [comment]
I just tested, and indeed, Win+Shift+Enter does not work on Windows 7.

As mentioned, you can change the shortcut in the preferences (`File ➜Preferences ➜Combo-Picker ➜ Shortcut`). If you need a suggestion, `Ctrl+Win+B` works fine for me.

I will make it the default shortcut for Windows 7.

**Comment by TerDale** [comment]
Hi @xmichelo,

I'm facing the same issue than @lucius346346. From my experimentations, it appears that itthe issue happens when <Shift> is part of the hotkey:

- as you stated, Ctrl-Win-B works,
- while Shift-Win-B works with a glitch: the b is displayed as if it was keyed in after the hotkey!
- this is why Shift-Win-Enter doesn't work: <Enter> is captured as keyed in, and without anything else the popup just closes.

**Comment by xmichelo** [comment]
Hi @TerDale 

Yes the issue is definitively linked to the fact that `Win+Shift` is reserved by Windows for switching language/keyboard layout.

I've already implemented the change but it did not make it to v4.0 that got released a bit earlier than I thought because of a bug. Starting with v5.0, The default shortcut for the Combo picker in Windows 7 is `Ctrl+Win+B`. For other versions of Windows, the default shortcut remains `Win+Shift+Enter`.

**Comment by TerDale** [comment]
Hi @xmichelo,

Just to mention that the default keyboard switching shortcut for W7 is instead Alt-Shift. So, the root cause should be elsewhere FMPOV. But anyway, not a big deal as long as you'll change Beeftext default for W7.

Anyway, thanks for your constant reactivity and your helpful app!
