### ISSUE TITLE
Message on Launch

### ISSUE THREAD

**Issue by teamayu** [xmichelo/Beeftext#188]
Everytime I start Beeftext, I keep getting this:

![02-09-2019-090846](https://user-images.githubusercontent.com/10624092/64085042-eab91d00-cd62-11e9-96fe-ba0631060918.png)

I`m using the portable version, win 10, 64bit.

Great application btw, thank you for offering it for free. :)

**Comment by xmichelo** [comment]
Hi. Normally, this message is displayed only the first time you launch Beeftext. This is determined by looking for a specific value in the file `Settings.ini` in the `Data` folder.

A potential cause for the issue is that the file is read-only. An easy fix would be to delete the `Settings.ini` file.

**Comment by teamayu** [comment]
Great, thank you. That appears to have worked. :)
