### ISSUE TITLE
Question: Date Calculation

### ISSUE THREAD

**Issue by andrewvink** [xmichelo/Beeftext#205]
Firstly - Great tool! I've been playing around with it and it's awesome

Question: 
Is it possible to have date manipulation?

Keyword Example  >>  Expands to

nxmon   next Monday (October 7, 2019)

nxtue   next Tuesday (October 8, 2019)

nxwed   next Wednesday (October 2, 2019)

nxthu   next Thursday (October 3, 2019)

nxfri   next Friday (October 4, 2019)

nxsat   next Saturday (October 5, 2019)

nxsun   next Sunday (October 6, 2019)

**Comment by xmichelo** [comment]
Hi @andrewvink.

It is not possible right now. It has already been requested to be able to use date and times other than 'now' (#111), but it will not solve your problem. 

It would be a nice addition.

**Comment by andrewvink** [comment]
Awesome thanks @xmichelo look forward to seeing the feature in the future!

**Comment by Cyprian-Mirewski** [comment]
Entering the date would then have to be more extensive.

As in:
https://textexpander.com/kb/general/how-can-i-enter-todays-date-with-textexpander/

For example in  textexpander: %@+15D%B %e, %Y will expand to show a “Month day, year” date 15 days in the future.

**Comment by xmichelo** [comment]
Hi. 
The solution I'm intending to implement is different, but with a similar flexibility.

`#{dateTime:<format>:<timeshift>}` where <timeshift> would be a series of time indication, like `+1y-1w`  (plus one year minus one week).

the duration indicators would be:
y: year
M: month
w: week
d: day
h: hour
m: minute
s: second
z: millisecond

Examples: 

`#{dateTime:yyyy-MM-dd:-7d}` will give you the date a week ago.
`#{dateTime:yyyy-MM-dd HH:mm:ss:+4h-10m}` will give you the date and time in 3h50m.

**Comment by xmichelo** [comment]
Hi.

Here are test builds for the feature:
- [Installer](https://1drv.ms/u/s!AjydspuvJDSngfFSMgXFAdNBojSd2A?e=cemkZh).
- [Portable Edition](https://1drv.ms/u/s!AjydspuvJDSngfFTprDVFaiSTp4rCg?e=t9VDy5).

In order to avoid ambiguity, I decided to invert the position of the 'time shift' and 'format' parts. So the new usage is:

`#{dateTime[:timeShift]:<format>`

Where <format> is the formatting instruction as currently implemented.
As mention above , timeShift is a series of time indication in the form <+/-><number><unit>, where unit must be one of the following:

y: year
M: month
w: week
d: day
h: hour
m: minute
s: second
z: millisecond

Examples:

`#{dateTime:+1y+1w:yyyy-MM-dd}` will evaluate to the date in 1 year and a week.
`#{dateTime:+2w-2h+1d:yyyy-MM-dd HH:mm:ss}` will evaluate to the date in two weeks minus 2h plus 1 day.

The `<format>` part can be empty, but the colon is required (e.g `#{dateTime:+1d:}`). In that case the format used is the one set in your system regional settings.
