### ISSUE TITLE
Button that maximizes the Edit Combo window to full screen

### ISSUE THREAD

**Issue by azdolinski** [xmichelo/Beeftext#214]
### Expected behavior
Possible to maximize the Edit Combo to full screen by standard window button next to close button (right-top corner)

### Actual behavior
In right top corner there is only button to close Edit Combo / there is no maximize/full screen button

### Steps to reproduce the behavior
Create or Edit Combo

### Operating system
Windows 10

**Comment by xmichelo** [comment]
Hi @azdolinski.
Indeed there is no maximize/minimize button  on the combo editor dialog. I could tell you that it's because it's a modal dialog that block the rest of the application interface until it is closed/cancel, but that still does not justify why you cannot maximize it.

I'll fix that in 6.1.
