### ISSUE TITLE
Beeftext in PortableApps

### ISSUE THREAD

**Issue by Cyprian-Mirewski** [xmichelo/Beeftext#218]
What do you think about PortableApps?
To distribute Beeftext in the .paf.exe file.

How to convince them to add you to the list of official PortableApps applications https://portableapps.com/apps

Maybe you would have to contact them?
https://portableapps.com/about/contact

**Comment by xmichelo** [comment]
I used to have a version of Beeftext in beta for the portableapps platform. I dropped it because I do not have much time to maintain a third form of distribution (beyond the installer and Portable Edition).

If I remember correctly, you can have the portable edition integrated in the portableapps app menu. Of course you will have to upgrade manually at every new release.

**Comment by Cyprian-Mirewski** [comment]
OK

Although maybe someday in the future it will be a good form of Beeftext advertising? :)
That more people will learn about Beeftext.

**Comment by Cyprian-Mirewski** [comment]
:(

I thought the following information was current:
https://github.com/xmichelo/Beeftext/wiki/Portable-Edition

> "PortableApps.com version
> Another portable variant developed for the popular PortableApps.com platform will soon be available."

**Comment by xmichelo** [comment]
The information was outdated. I removed this paragraph. Thanks.
