### ISSUE TITLE
[Bug] Beeftext does not expand in Hyper terminal app

### ISSUE THREAD

**Issue by scott-b-gilbert** [xmichelo/Beeftext#284]
#### Expected behavior
Snippet expanded

#### Actual behavior
Instead of expanding the snippet, the text is actually cleared out.

#### Steps to reproduce the behavior
1. Install Hyper terminal from hyper.is.
2. Type a snippet to be expanded.

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
v7.1

#### Operating system version (e.g Windows 10)
Windows 10

**Comment by xmichelo** [comment]
Hi.

The reason this happens is that Hyper terminal does not support pasting via `Ctrl+V`. Beeftext needs to synthesize a Ctrl+V in order to insert the content of the snippet. 

Fortunately, there is a solution. Go to `File ➜ Preferences ➜ Advanced ➜ Sensitive Applications`, and had `Hyper.exe` to the list.
Beeftext will now be aware that `Ctrl+V` is not available for that executable, and instead will type all the letters of the snippet one by one. Its slower as I have to add a short delay between keystrokes to avoid crashes, but at least it works.

I'm aware that pasting is done by using the `Shift+Ins` shortcut, but for some reasons, I cannot generate the shortcut programmatically.
