### ISSUE TITLE
[Feature] Collaborative developpement

### ISSUE THREAD

**Issue by mathieucaroff** [xmichelo/Beeftext#298]
I would like to participate in the development of Beeftext, however, I don't know how to build it.

https://github.com/xmichelo/Beeftext/tree/c0eea17fd116d85feced959cb41d4d6cf4767d92#building-beeftext

> Detailed build instructions are not available at the moment.

I'd be interested if you could spend a bit of time explaining go into some level of details about how to build Beeftext, and how to test it manually. Alternatively or in complement, we can use this issue to discuss the installation, with me asking for help whenever I feel helpless. In such a case, I can summarize the whole developement environment installation procedure once we're done.

Have a good day

**Comment by xmichelo** [comment]
Hi @mathieucaroff 

Thank you for your interest in contributing. Unfortunately, and even if this it may look strange, I am **not** looking for contributors. Even further I will not look at an PR submitted.

The reason is simple: I'm busy as with my day job as an engineer, and I have a maximum of 4 to 5 hours to spend on Beeftext per week. A good portion of this is spent dealing with issues. I want to keep the rest of my time for actual development, not discussion or code reviews.

That said, you can still build Beeftext for your own pleasure. What you need is to setup Qt for development with Visual Studio:

1. Install [Visual Studio 2019](https://visualstudio.microsoft.com/downloads/) (the free Community edition is sufficient).
2. Install [Qt](https://www.qt.io/download-qt-installer): The online installer will require a free account. From the options, grab the latest release (5.15.1 as I write this message), The only component you need is `MSVC 2019 32-bit`, and in the `Tools` section, grab OpenSSL.
3. In Visual Studio 2019, install the `Qt Visual Studio Tools` extension from the Marketplace (`Extensions ➜ Manage Extensions ➜ Online), and [configure it](https://doc.qt.io/qtvstools/qtvstools-managing-projects.html#managing-qt-versions).

You should now be able to open and compile the Beeftext VS solution `Beeftext.sln`
