### ISSUE TITLE
[Feature] Command Line Helper

### ISSUE THREAD

**Issue by harun** [xmichelo/Beeftext#306]
Is it possible to use beeftext with the Command. 
I tried but combo picker or combo trigger keyword not working.
I would like to use beeftext like command line helper.

Thank you.

**Comment by xmichelo** [comment]
It does not work by default on older systems because Ctrl+C / Ctrl+V does not work for copy/paste. 2 solutions:

1. In the latest versions of Windows 10, you can enable Ctrl+C / and Ctrl+V in the options: check the `Enable Ctrl key shortcuts`.
2. In the Beeftext preferences, click on the `Sensitive applications` button in the `Advanced` tab, and add  `cmd.exe` to the list.

Note: for some user, Beeftext does not work with advanced terminal application such as ConEmu
