### ISSUE TITLE
[Feature] Preference: launch Beeftxt at startup windows

### ISSUE THREAD

**Issue by weber158** [xmichelo/Beeftext#321]
For the next release, please,
best regards,
jpweber@orange.fr
 dimanche  8th novembre, 2020

**Comment by xmichelo** [comment]
Hi.

It's already implemented. In the behaviour (Comportement) tab, check the 'automatically start Beeftext at login'. (Démarrer Beeftext automatiquement à la connexion).

Note that this option in only available in the 'installer' based version of Beeftext, not in the 'Portable Edition'.

**Comment by zigboom** [comment]
I understand the logic of not including it in the portable version, but still it will be useful if it's added and not activated by default. I guess some people like me prefer the portable version, even if it's used on just one computer most of the time or all the time. 
Of course, it's possible to add it manually to the startup folder, which I did, but the program starts with an open window instead of minimized, so it will need more tinkering to make it work properly. Please add it for convenience :)

**Comment by ElimGarak72** [comment]
I second this, please add the feature. Thank you!
