### ISSUE TITLE
[Feature] Add Preference to Minimize to Tray Instead of Taskbar

### ISSUE THREAD

**Issue by SpiralInSpace** [xmichelo/Beeftext#334]
I like to see a preference option for the application to minimize to the tray instead of the taskbar.   Maybe to extend it to the close X button as well so that when you click the X to close the app, then it will minimize the application to the tray.

Thank you!

**Comment by xmichelo** [comment]
Hi. At the moment
- The `The `Close` button is equivalent to 'minimize to tray'.
- The `Minimize` button minimize to the taskbar.
- To exit the application, there are two options:
   1. Right click on the tray icon, then `Exit Beeftext`
   2. From the main menu `File ➜ Exit Beeftext`.

I like this approach because all three ways to get rid of the main window are covered.
