### ISSUE TITLE
[Feature] Option to change Combo Picker window size

### ISSUE THREAD

**Issue by dp1702** [xmichelo/Beeftext#359]
Could you please add an option to change the Combo Picker window size?

It seems locked at 442 x 319 pixels and some long combo names aren't fully displayed.

If the window could be resized by dragging the corners it would solve most of my issues.

A preference to change the window and the font sizes would be great.

Thank you very much.

**Comment by xmichelo** [comment]
Hi. Thanks for the suggestion. 

As the window is borderless, it requires a bit of work on my side, but I will make the combo picker window resizable in the next release. The size changes will be saved in order to preserve it when the application is restarted (position will not, as the picker window always appears centered over the currently active window).

**Comment by xmichelo** [comment]
It should be fixed. Here are test builds. Let me know if it fixes the problem for you.

- [Beeftext-9.0-Installer.zip](https://github.com/xmichelo/Beeftext/files/6791051/Beeftext-9.0-Installer.zip)
- [Beeftext-9.0-PortableEdition.zip](https://github.com/xmichelo/Beeftext/files/6791052/Beeftext-9.0-PortableEdition.zip)
