### ISSUE TITLE
Microsoft's PowerToys Keyboard Manager breaks BeefText

### ISSUE THREAD

**Issue by remorsecodex** [xmichelo/Beeftext#375]
Issue: Using the Keyboard Manager built into Microsoft PowerToys makes all Combos produce blank results. The sound still plays, the keyword is correctly removed, but the snippet never appears.

Disabling or otherwise turning off the Keyboard Manager (which allows re-binding keys) immediately resolves the issue, however for those who need to re-bind keys, this isn't a sustainable option.

Further info: I swap alt and control on my keyboard (old habits from macos) so if BeefText works by copy and pasting the Snippets, that may be the break point. Perhaps there could be a new option to change which keyboard shortcuts beeftext uses to do its magic?

**Comment by xmichelo** [comment]
Hi.

According to my testing the problem is not the Keyboard Manager from the MS Powertoys itself, but the fact that you swap Ctrl and Alt. In order to perform combo substitution in a way that works in nearly all application, Beeftext generates a Ctrl+V command to paste the snippet. Unfortunately, with your settings, the Keyboard manager converts this to Alt+V, which at best does not paste anything, and at worst, may open a menu in your application if a menu accelerator is set with the 'V' key.

Here are test builds that use `Shift+Insert` instead of `Ctrl+V` to trigger the pasting of the snippet. Let me know if it fixes your issue. In that case, I will implement a setting in the advanced preferences to select which shortcut to use. I don't want to switch entirely to `Shift+Insert` as I'm not sure it is as universal as `Ctrl+V`.

- Installer: [Beeftext-9.0-Installer.zip](https://github.com/xmichelo/Beeftext/files/6759941/Beeftext-9.0-Installer.zip)
- Portable Edition: [Beeftext-9.0-PortableEdition.zip](https://github.com/xmichelo/Beeftext/files/6759944/Beeftext-9.0-PortableEdition.zip)

**Comment by remorsecodex** [comment]
Thanks. This seems to resolve it. You're right that shift+ins probably won't work universally, but even having one alternative to use as a workaround is a wonderful help for those of us who rebind. Nicely done!

**Comment by remorsecodex** [comment]
Ok, so I thought it was working, but it turned out that I had forgotten to enable my rebinds in PowerToys (basically Left Alt = Left Ctrl and Left Ctrl = Left Alt).

As long as those bindings are set, even the shift+ins advanced setting being on still results in no paste. The keyboard shortcuts for pasting (shift+ins and alt+v with the rebind) both work though, just not the macro that BT uses.

**Comment by remorsecodex** [comment]
> Ok, so I thought it was working, but it turned out that I had forgotten to enable my rebinds in PowerToys (basically Left Alt = Left Ctrl and Left Ctrl = Left Alt).
> 
> As long as those bindings are set, even the shift+ins advanced setting being on still results in no paste. The keyboard shortcuts for pasting (shift+ins and alt+v with the rebind) both work though, just not the macro that BT uses.

I just got pushed the stable 9.1 and the shift+ins toggle seems to work for insertion now. Nicely done. Very much appreciate the option of another method, will be a big help to people who rebind in the future. 👍

**Comment by remorsecodex** [comment]
So in the meantime, my workaround fix is that I quit using the PowerToys keyboard manager and went back to SharpKeys (which regedits the bindings). For whatever reason, this method of rebinding doesn't seem to have any issues with BeefText operations.

**Comment by xmichelo** [comment]
I guess the powertoys keyboard manager operates at a lower level in the 'keyboard' stack.
