### ISSUE TITLE
Lost my combos unexpectedly - and hadn't backed up!

### ISSUE THREAD

**Issue by alstevneson** [xmichelo/Beeftext#415]
I wasn't expecting to lose the combos

They all disappeared: no restart, no PC crash, the only event was resetting Microsoft Outlook 365 password.

Beeftext version 11.1 for Windows 10 desktop PC

I will backup from now on - maybe worth highlighting the risk?

**Comment by xmichelo** [comment]
First time I hear about such problem since one of the very first beta.

There is an auto-back mechanism that keeps tracks of the last 50 modifications  (Files➜Preferences➜Advanced➜Automatic backup).
You can also try to locate the combo list file using the Windows file search. it's a text file named `comboList.json`.

**Comment by alstevneson** [comment]
Sorted thanks. Found them

I think the cause was a Microsoft issue not a Beeftext problem
