### ISSUE TITLE
[Bug] If you comma delimit text, auto complete fails

### ISSUE THREAD

**Issue by teamayu** [xmichelo/Beeftext#418]
v11.1 (Portable)
Windows10, 64 Bit

Firstly, thank you for this superb free software. :)

This has been a problem for awhile, but when I add a comma, the next auto replace doesn't work. For example, I have two combos set:

keyword = **abc**, replace with **123**
keyword = **def**, replace with **345**

Type **abc** and **123** appears, but then type a comma and do **def**, nothing happens. Hope that is enough info?

Thank you.

**Comment by xmichelo** [comment]
It's a normal behavior. `,` is not considered as a 'word delimiter', so that it can be used as part of a keyword. Your example does not trigger the substitution of `def` because Beeftext supposes you are typing the keyword `,def`, which does not match if the matching mode is set to *Strict*.

The solution to your problem is to switch the matching mode to *Loose* instead of *Strict* (at a global level in the preferences, or for a particular combo in the combo editor dialog. You can learn about the matching mode in the [dedicated wiki page](https://github.com/xmichelo/Beeftext/issues/418).

**Comment by teamayu** [comment]
Thank you for the info. Sorry, thought it was a bug as similar software works fine.
