### ISSUE TITLE
Getting entry point not found error message when updating to beeftext 0.12

### ISSUE THREAD

**Issue by Celesian** [xmichelo/Beeftext#432]
![image](https://user-images.githubusercontent.com/49375840/140380534-fa0e98aa-ff7c-44fb-b46d-953039055bd0.png)

On windows 7 beeftext version 11 worked fine

**Comment by xmichelo** [comment]
The problem is that Beeftext uses the Qt framework. Since the release of Qt 6, they officially [stopped supporting Windows 7 and 8](https://www.qt.io/blog/qt6-development-hosts-and-targets). By chance, it was working with the first release. It simply does not work anymore, and there is nothing I can do about it.

You reinstall Beeftext v11.1, the downgrade will not cause trouble.
