### ISSUE TITLE
[Bug] Update check fails in v12.0

### ISSUE THREAD

**Issue by Keek** [xmichelo/Beeftext#445]
Update checks fail since upgrading to v12.0 (checking for update was working properly until now), computer has working internet connection (via VPN), possibly an issue with a corporate proxy

**Comment by xmichelo** [comment]
Hi.

Thank you for reporting. There is a chance it due a an outdated DLL shipping in the beeftext. I'll check that.

**Comment by xmichelo** [comment]
The problem is fixed. Please have a look at the following builds:

- [Beeftext-12.0-Installer.zip](https://github.com/xmichelo/Beeftext/files/7783436/Beeftext-12.0-Installer.zip)
- [Beeftext-12.0-PortableEdition.zip](https://github.com/xmichelo/Beeftext/files/7783438/Beeftext-12.0-PortableEdition.zip)

If the issue persists, please re-open this issue.
