### ISSUE TITLE
CreateDXGIFactory2 error on Windows 7

### ISSUE THREAD

**Issue by Shilly23** [xmichelo/Beeftext#451]

**Comment by xmichelo** [comment]
Hello.

There is probably a component missing somewhere in Windows, I used to test Beeftext in a VM with a fully patched version of 7 and never had this problem.

Please note that since v12, Beeftext is not supported on 7. See [the announcement](https://twitter.com/beeftext/status/1456505466972934159). I learned it to late to put an announcement in the application itself.
