### ISSUE TITLE
System hiccup and cursor freezing when loading beeftext

### ISSUE THREAD

**Issue by hiren1610** [xmichelo/Beeftext#48]
Hi,

I am really impressed with this little tool you have developed that is free of cost and I really appreciate that. This saves me a lot of keystrokes everyday.

I have just noticed an issue that I would like to report.

When loading Beeftext, my cursor is freezing on screen until the Beeftext loaded completely and I can see the icon in my taskbar. I am using Windows 10 x64.

Please shed some light on this issue.

Thanks.

**Comment by xmichelo** [comment]
Hi @hiren1610 . Thank you for your feedback and support.

There is indeed a freeze of the mouse at startup, and I guess it can last longer depending on the speed of your computer.

Unfortunately there is not much we can do about it. Beeftext relies on a feature of Windows called [hooks](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644959(v=vs.85).aspx), so that the program is notified by the operating system when the user presses a key or performs a mouse action, in any application. The setup of the mouse hook is what causes the freeze.

You may wonder why Beeftext needs to be notified of mouse events. The application only checks for mouse clicks (not motion) because it needs to reset the combo whenever you click. Without that mechanism, you could type the first two letters of a combo keyword, click to move the text cursor to a different position, then type the remaining keyword letters. This would trigger the combo, leading to unwanted results.
