### ISSUE TITLE
[Feature] Hide Icon

### ISSUE THREAD

**Issue by pityalvarez** [xmichelo/Beeftext#480]
**Is your feature request related to a problem? Please describe.**
I always see the "transparent" icons of windows volume control and internet status, with white lines like most of the taskbar. Now, I have my only application open, Beeftext icon, with a different colour, that can't be changed and can't be hidden.

**Describe the solution you'd like**
I thought about an option to hide the icon, as simple as that.

![image](https://user-images.githubusercontent.com/97750378/156096569-6efad97a-b975-41c7-9a04-142997731e9c.png)

**Comment by xmichelo** [comment]
Hi.

Thank you for your feedback. Because it's a sensitive application listening to what you type), we need to have a indicator that beeftext is running. I will not add an option to remove the icon from the notification area in the taskbar. 

However, if you do not want to see the Beeftext icon, you always have the option to send the icon to the overflow menu of the notification area. You can find instructions in [this support page](https://support.microsoft.com/en-us/windows/customize-the-taskbar-notification-area-e159e8d2-9ac5-b2bd-61c5-bb63c1d437c3)
