### ISSUE TITLE
Combos not working after v14.0 update

### ISSUE THREAD

**Issue by Keek** [xmichelo/Beeftext#493]
After updating to Beeftext v14.0 Portable Edition I have noticed that in certain applications (e.g.: KiTTY Terminal) the combos stopped working, after entering the keyword the text input is erased but the combo is not expanded. Everything was working OK up until the update.

**Comment by xmichelo** [comment]
Hi.

Beefext relies on Ctrl+V to paste snippets. Some applications do not support Ctrl+v for pasting, mostly terminal apps like Kitty, Putty, etc... 

Beeftext has a list of 'sensitive applications' for that purpose, for which Beeftext does not Copy/Paste snippets, but type them one character at a time. You can access this list in `Preferences➜Advanced➜Sensitive Applications`, and add executable names in the window.

There used to be a built-in list of application, that were not displayed in the windows but were widely used and know to not support Ctrl+V. I removed this list in v14.0. because it was not visible, and not editable. This was probably not a good idea. 

The list contained the following items:
```
- mintty.exe
- putty.exe
- powershell.exe
- kitty*.exe
- ConEmu*.exe
```

I will restore this list. Please see #494 to track progress.
