### ISSUE TITLE
Installed Beeftext on Win 8.1, and when I try to run it, I get an error saying "No Qt Platform Plugin Could Be Initialized"

### ISSUE THREAD

**Issue by Studly** [xmichelo/Beeftext#504]
I've tried both the full install and portable version and get that error on both. 

Looking up how to fix that error, some sites say to search your PC for the folder "pyqt5_tools" and then copy and paste part of that into the desination, which I assume is BeefText's folder? However I searched and don't have that "pyqt5_tools" folder on my PC. 

Can someone give me detailed instructions on how to fix that error so I can run Beeftext please? Thanks, much!

**Comment by xmichelo** [comment]
Hi. 

Beeftext will not run on Windows 8.x, because it is built upon the Qt Framework that does not support it anymore.

See [this page](https://github.com/xmichelo/Beeftext/wiki/Older-versions) for details. I do not have access to Windows 8 anymore. I'm not sure what is the last compatible version.

**Comment by Studly** [comment]
Thanks for the reply and explanation!
