### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by juenfam** [xmichelo/Beeftext#520]
#### Expected behavior 
when typing my keyword from BeefText in the "Thinkorswim" windows 10 application password field the snippet does not appear, only the 3 characters of my keyword appear with and error I typed the wrong password.
#### Actual behavior
The 3 characters of my keyword appear with and error I typed the wrong password.
#### Steps to reproduce the behavior
Enter a keword from BeefText in the password field of the "Thinkorswim" windows 10 application
#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
Beeftext v7.0 Portable Edition
#### Operating system version (e.g Windows 10)
![2022-10-22_10-16-15](https://user-images.githubusercontent.com/116448559/197347261-d27864f3-656e-4b85-bf20-7bdeaba5b292.png)
Thanks,
Mark

**Comment by xmichelo** [comment]
Hi. If Beeftext works in other applications, the problem is not Beeftext, but thinkorswim. There is a change they protect their password fields against external actions, which Beeftext requires.

Also please: [do not use Beeftext to store passwords](https://twitter.com/beeftext/status/999001649590034438).
