### ISSUE TITLE
Is there  with excel way to direct import data?csv import is a bit complex(many steps)[Feature] 

### ISSUE THREAD

**Issue by s6677** [xmichelo/Beeftext#534]
At present, there is no problem in importing csv data, but it requires a lot of processing steps. The csv data structure is very simple, but due to some symbol problems and no column headers and the handling of character garbled problems(character encoding problem),If you use excel to make csv, you will encounter these problems, and then Imported data is always incorrect or garbled characters, It took me a long time to understand the logic of  with excel to make csv, In the end, I still use csv macro code of excel to solve the problem . This process may be a headache for some people who have no patience to query. If I can't find the csv macro code, I may still have a hard time importing the correct data,Hope to provide a way to directly import data with excel.

**Comment by decard123** [comment]
why do you say that is complicated? it seems very simple to me,

**Comment by s6677** [comment]
Because the tools I use are mainly microsoft excel to make csv,When
exporting, characters appear wrong and garbled(If the text is not in
English, other text will appear confusing)，I spent a long time dealing with
this problem,with the microsoft excel ，This looks like a problem with the
conversion.

decard123 ***@***.***> 于 2022年12月17日周六 下午7:24写道：

**Comment by decard123** [comment]
ahh. that is a different issue. concidently just a few days ago i logged a bug where the import into Beeftext mangled all theh characters that have diacritics which seems to be a similar issue

so the fix needed is to Beeftext import with the character set it is using during import (because, as for you, it (obviously) is displaying correctly in Excel before import (but i think character set you need will be more difficult than mine eg â

in fact maybe the fix is to be able to select what character set to use?

**Comment by decard123** [comment]
of course, in my case, i can fix (i think) by typing those characters directly into Beeftext, but sort of defeats the purpose; and i suspect that using the CHAR() function prob won't work either

but this issue is very important because one of the most normal and useful 'use cases' for Beeftext is to have foreign language snippets

**Comment by s6677** [comment]
export  csv  from microsoft excel,then  direct import to beeftext ，In other
languages ​display confusion(not english), I remember


   1 seems [  character selection problem]
   2 your csv data format , each cell data，seems to contain hidden ["each
data"]    👉[""]


,I'm not  sure, but I remember I dealt with this problem for a long time to
solve it,Finally, using excel's csv macros solved the problem,It's hard for
me to solve without finding this macro

seems to be the reason for the above

decard123 ***@***.***> 于 2022年12月18日周日 下午1:26写道：

**Comment by s6677** [comment]
First , I found the character selection problem, but it seems to have no
effect after selection, Then use excel's csv macro export csv，display
correctly

So the two points above，I'm not sure 1 or 2

power k y scy ***@***.***> 于 2022年12月18日周日 下午1:41写道：

**Comment by decard123** [comment]
no. the answer i eventually found in a post on-line was this and is actually very simple!

simply do a 'Save As', and select CSV (UTF-8) as the file type

worked like a dream, and when i opened the subsequent file in Notepad to check, there were all my diacritics.

i exported that file into BT, all my diacritics were preserved

so to reiterate - THE PROBLEM WAS NOT A BT PROBLEM!

**Comment by xmichelo** [comment]
Hi.
Indeed, Beeftext is expecting UTF-8 encoding to properly cope with non ASCII characters. I've added a line in the [wiki page](https://github.com/xmichelo/Beeftext/wiki/Import-and-export).
