### ISSUE TITLE
Should add a function to show pickwindow automatically, it will be super powerful and have huge advantages[Feature] 

### ISSUE THREAD

**Issue by s6677** [xmichelo/Beeftext#536]
I have a similar app on my phone, it is name (typing hero in play store ),It provides the function of automatic pick window, it is An automatic pop-up reminder function, if it is needed, You can choose to replace immediately, which is super powerful and has huge advantages. If you don't understand the following, you can go to the play store to download this app, you will soon understand what I mean.
Pick window Usually we forget something, then call and open the search.

But if you set two characters or other quantity, then any input moment,Then automatically monitor the two characters on the left side of the text cursor. If a hot word or hot word content is matched, Only need to match two of the characters,it will automatically display the matched content in the pick window.   If what is displayed is what you need, you can replace it immediately by operating pickwindow or shortcut keys.
It will remind you at any time, you don't need to type the exact hot word or hot word content, just need to be two characters next to each other, 

You just need to have a little impression ，You can jog your memory with plain language, so the hot words you create will also be very simple, You can create hot words in descriptive language, no need to remember anything，after a while you will remember everything

**Comment by xmichelo** [comment]
Popping a window out of the blue when you are not the active application is not possible (or very tricky) because Windows has a safety mechanism that prevents background applications from displaying a window and steal the focus.  This is intended to prevent malicious behaviors. The window will likely appear under the currently active window, with a blinking icon in the taskbar.

Picker windows works fine because it is triggered by a global shortcut.
