### ISSUE TITLE
Not expanding combos in CLI clients

### ISSUE THREAD

**Issue by viktorix** [xmichelo/Beeftext#62]
### Expected behavior
-Typing in a combo should expand it into proper text

### Actual behavior
- Typing in a combo replaces it with nothing

### Steps to reproduce the behavior
- Using [PuTTY](https://www.putty.org/) you need to connect to server via SSH to access CLI and try using combos there.
- The issue also happens in PowerShell. Launch PowerShell CLI and try a combo.

### Operating system
- Windows 10

I tried it in Command Prompt on Windows and **it does work**.

**Comment by xmichelo** [comment]
Hi @viktorix.

I noticed the problem with **Putty**, and forgot to open an issue for it, so thanks for reporting it.

The reason Beeftext does not work properly is that Putty does not support the standard `Ctrl+V` shortcut for pasting the content of the clipboard. To work as universally as possible, The combo substitution process is  the following: 

- Backup the content of the clipboard.
- Copy the snippet to the clipboard.
- Synthesize a `Ctrl+V` keystroke. 
- Restore the previous content of the clipboard after waiting for a brief amount of time.

I'm surprised to hear that Beeftext is not working in **PowerShell**, because it works just fine on my Windows 10 system.

There is a workaround that I can implement for Putty (and other terminal applications like Cygwin), because there is another standard shortcut for pasting: `Shift+Insert`. It also works nearly everywhere, but unfortunately, there are also applications that does not support it, such as... PowerShell. As a consequence, I'll have to try to identify the active application and if it is in a predefined list, I'll use `Shift+Insert` instead of `Ctrl+V`.
