### ISSUE TITLE
Any idea why it is not working with KiTTY (a PuTTY fork?)

### ISSUE THREAD

**Issue by TerDale** [xmichelo/Beeftext#96]
### Expected behavior
Typing a combo keyword in a KiTTY terminal window, this one should be replaced by the associated snippet defined in Beeftext

### Actual behavior
Once the combo keyword is completed keyed in, it is cleared off, and the cursor is back to first position

### Steps to reproduce the behavior
Just define a new combo, and type its keyword in a KiTTY term.

### Operating system
Windows 7, KiTTY 0.70.0.5

Otherwise Beeftext is great, but can't continue with it if not working in KiTTY, as using it every day!
Anyway, thanks for making Beeftext available free!

**Comment by xmichelo** [comment]
Hi @TerDale.

Thanks for reporting the issue.

Beeftext works by 'faking' a copy/paste operation of the snippet using the *nearly* universal `Ctrl+V` keyboard shortcut. However, there are a few applications that do not respond to this shortcut, and this includes terminal emulators like Kitty or Cygwin's mintty. These applications respond to the alternative `Shift+Insert` command, but unfortunately, trying to synthesize this shortcut does not trigger a paste event.

A workaround for this issue is already in place. Beeftext has a list of 'sensitive' executable files. If Beeftext is about to perform a combo substitution and the active application's executable name is in the list, instead of using copy/paste, it simply types all the letters constituting the combo snippet one after the other. It's slower, and does not work as universally as the normal method, but it works most of the time.

Currently, this list of sensitive applications is hard-coded and contains the executable files `mintty.exe`, `putty.exe`, and `powershell.exe`. I will now add `kitty.exe` and `kitty_portable.exe` to the list. I will also add a GitHub issue to remind me that this list should be made editable by users at some point.

I will quickly build an unofficial installer for you to try. Stay tuned.

**Comment by xmichelo** [comment]
Fixed by f4456db.

@TerDale you can test using the attached test builds.

[Beeftext-1.5-Installer.exe.zip](https://github.com/xmichelo/Beeftext/files/2263839/Beeftext-1.5-Installer.exe.zip)
[BeeftextPortableEdition.zip](https://github.com/xmichelo/Beeftext/files/2263836/BeeftextPortableEdition.zip)

**Comment by TerDale** [comment]
Hello Xavier,
Je viens de me rendre compte que tu étais aussi Français ;-)
Anyway, I continue in English, in order that the thread can be useful for more people.
So, thanks for your terrific support: prompt reply, along with a fix!

I just tried it, and well... it is somehow working. I mean that it works for some of my combos, but for others it repeats some characters: for instance for the combo 
From what I can see, it seems to be the case with combos having numbers mixed with letters in the same "word". For instance :
- "6tpwy4vye6J3" expands once as "6tpwy46vtypew6yJ43vye6J3", the next time as "6tpw6yt4pvwyye64Jv3ye6J3"
- while combos with words made of letters only expand properly, as is the case for dates (using your #{date} and #{dateTime} macros.

So, it sounds a bit weird to me, any clue?

FWIW, I also tried Auspex and TyperTask, and they both work with KiTTY, without such unexpected behavior. However I don't how they insert the replacement text in the used app. 
But I'd like to stick with Beeftext as being more ergonomic, open source and actively maintained ;-)

Thanks for your help

**Comment by xmichelo** [comment]
Hi @TerDale. 

Oui effectivement je suis français 😉.

I cannot get to reproduce the problem. The combo you gave as an example just work every on my Windows 10 PC.

I'm interested in fixing this issue, so I'm re-opening it. Before giving up, and if you are OK to give me a hand I'm interested in the following:

1. A exact copy of a combo that fails in Kitty. (select it, right click ➜Export, and send me the JSON file).
2. Does it fail in all application you are remotely running? (shell, vi, emacs, whatever)
3. What language and keyboard layout are you using on the local machine?
4. Do you have the same problem if you use Putty?

Thanks in advance.

**Comment by TerDale** [comment]
Hi @xmichelo,

My bad! Sorry for having lost your time, I just figured out that this issue happened because I forgot stopping TyperTask. So, it was also running, while having the same trigger and combo! :-P Really sorry...
So, it works fine actually.

However, may I request that you add also ConEmu*.exe in your exception list, please? Indeed, I use to embed my KiTTY sessions as tabs in [ConEmu](https://conemu.github.io/), and I spotted that, while your fix works with KiTTY ran as standalone, the same behavior than before still occurs when it is embedded in ConEmu. Thanks in advance!

**Comment by xmichelo** [comment]
Hi @TerDale 

No problem. I have added ConEmu*.exe to the exception list. Support for wildcard was not implemented but it was straightforward so I did it (in c8dae3c). Here is test build. I quickly tested with ConEmu, and it seem to work fine with both CMD.exe and putty sessions.

[Beeftext-1.5-Installer.zip](https://github.com/xmichelo/Beeftext/files/2281080/Beeftext-1.5-Installer.zip)

**Comment by TerDale** [comment]
Hi @xmichelo,

Sorry, was OOF last week, and thus didn't have a chance to test your build. 
Anyway, I saw this morning that you released 1.6, thanks for having added ConEmu!
And kudos for your great support, really!
