### ISSUE TITLE
Is Transparent operation possible?

### ISSUE THREAD

**Issue by gfoster00** [xmichelo/Beeftext#99]
Would it be possible to make the operation of BeefText transparent with respect to the clipboard? i.e. leave the current clipboard contents intact, either by using some separate clipboard, or the simple option of saving the current clipboard, replacing and pasting the text and then restoring the original clipboard? That way anything the user has in the clipboard prior to expanding text isn't erased?

**Comment by gfoster00** [comment]
Oh - that's what it does do. I must have messed up my original testing! Thanks

**Comment by xmichelo** [comment]
Indeed, Beeftext is restoring the clipboard after use, but there are a few caveats:
- In order to work properly there is a delay before the original clipboard content is restored after the combo substitution. Currently, the delay is 1 second.
- Beeftext can only restore the clipboard if it contains text, HTML, colors, images or file paths.
